config:
  file:
    base-path: "./songs"
  jwt:
    expiration: 86400000
    secret-key: "da11bb2a86a7b7cb2a6aa3e2423a749ba5f4e5f9e26f5d3430af4518d40757b0"
org:
  jobrunr:
    background-job-server:
      enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/music
    username: vkaelin
    password: password
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs
